[package]
name = "lade"
version = "0.1.0"
edition = "2021"
description = "Load automatically env variables from different sources."
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.68"
self_update = { version = "0.34.0", features = ["archive-zip", "rustls", "compression-zip-deflate"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
clap = { version = "4.1.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1.7.1"
