[package]
name = "lade-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-process = "1.6.0"
async-trait = "0.1.64"
futures = "0.3.26"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.7.1"
serde_json = "1.0.93"
url = "2.3.1"
